#!/bin/bash
#
#----------------------------------------------#
# Contributor: Tobias Holzmann                 #
# Last Change: February 2015                   #
# Topic:       Multiregion meshing             #
# Email:       Tobias.Holzmann@Holzmann-cfd.de #
#----------------------------------------------#


#-------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean


#-------------------------------------------------------------------------------
echo -e "
-------------------------------------------------------------------------------
Tutorial by Tobias Holzmann
Generated February 2015
OpenFOAM-2.3.x
-------------------------------------------------------------------------------


Topic: sphere meshing in a channel with layers 
-------------------------------------------------------------------------------"


#-------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#-------------------------------------------------------------------------------
echo -e "   - Create STL files"
cat cad/stlChannel/* > constant/triSurface/channel.stl
cp cad/stlSphere/sphere.stl constant/triSurface/sphere.stl


#-------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logFile


#-------------------------------------------------------------------------------
echo -e "   - Create feature edges"
surfaceFeatureExtract >> logFile


#-------------------------------------------------------------------------------
echo -e "   - Meshing the fluid domain with snappyHexMesh (cut out sphere)" 
snappyHexMesh >> logFile


#-------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n\n
"


#-------------------------------------------------------------------------------
